name: "Execute SOPS Command"
description: "Sets up SOPS, provides the AGE key, and executes a specified SOPS command."

inputs:
  sops-age-key:
    description: "The AGE private key for SOPS operations."
    required: true
  sops-args:
    description: "Arguments to pass to the SOPS command (e.g., '-e -i secrets.yaml' or 'updatekeys secrets.yaml')."
    required: true
  sops-version:
    description: "The version of SOPS to install (default from install-sops action)."
    required: false
    default: "v3.10.2" # Matches the default in your install-sops action
  working-directory:
    description: "The working directory to run the sops command in."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install sops
      uses: ../install-sops # Assuming it's in the same repo, adjust path if deployed separately
      with:
        sops-version: ${{ inputs.sops-version }}

    - name: Execute SOPS command
      shell: bash
      run: sops ${{ inputs.sops-args }}
      env:
        SOPS_AGE_KEY: ${{ inputs.sops-age-key }}
      working-directory: ${{ inputs.working-directory }}

branding:
  icon: "lock"
  color: "blue"
