name: "Load SOPS Secrets"
description: "Decrypts a sops file and loads secrets into the environment"

inputs:
  sops-age-key:
    description: "The AGE private key for SOPS decryption"
    required: true
  sops-file-path:
    description: "Path to the SOPS encrypted file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install sops
      uses: ./.github/actions/install-sops
      with:
        sops-version: ${{ inputs.sops-version }}

    - name: Decrypt and Load Secrets from SOPS
      shell: bash
      run: |
        echo "Decrypting secrets from ${{ inputs.sops-file-path }}..."
        sops --decrypt ${{ inputs.sops-file-path }} | grep -v '^#' | grep -v '^$' | while IFS= read -r line; do
          # Extract key (everything before the first '=')
          key="${line%%=*}"
          # Extract value (everything after the first '=')
          value="${line#*=}"

          # Check if key and value extraction worked reasonably and value is not empty
          if [ "$key" != "$line" ] && [ -n "$value" ]; then
              echo "::add-mask::$value"
              echo "$line" >> $GITHUB_ENV # Add the original KEY=VALUE line to env
          else
              echo "Warning: Skipping line, could not parse KEY=VALUE: $line" >&2
          fi
        done
        echo "Secrets masked and loaded into environment."
      env:
        SOPS_AGE_KEY: ${{ inputs.sops-age-key }}

branding:
  icon: "lock"
  color: "yellow"
